import type { GuidedLessonSequence } from '../engine/GuidedLessonTypes';

export const anisotropyData: GuidedLessonSequence = {
  id: 'anisotropy',
  titleEn: 'Anisotropy and Isotropy',
  titleBn: 'অসমদিকতা এবং সমদিকতা',
  steps: [
    {
      id: 'step-1-crystal-structure',
      titleEn: 'The Crystalline Structure',
      titleBn: 'স্ফটিকাকার গঠন',
      narrationEn: 'Consider a 2D crystalline solid composed of two different types of ions.',
      narrationBn: 'দুটি ভিন্ন ধরণের আয়ন দ্বারা গঠিত একটি দ্বিমাত্রিক স্ফটিকাকার কঠিন পদার্থ বিবেচনা করুন।',
      whatHappenedEn: 'An ordered array of alternating blue and red particles appeared.',
      whatHappenedBn: 'নীল এবং লাল কণার পর্যায়ক্রমিক একটি সুশৃঙ্খল বিন্যাস দৃশ্যমান হয়েছে।',
      whyItHappenedEn: 'This represents a perfect crystal lattice where particles are arranged periodically.',
      whyItHappenedBn: 'এটি একটি নিখুঁত স্ফটিক জালককে নির্দেশ করে যেখানে কণাগুলি পর্যায়বৃত্তভাবে বিন্যস্ত থাকে।',
      observeEn: 'Notice the alternating pattern.',
      observeBn: 'পর্যায়ক্রমিক বিন্যাসটি লক্ষ্য করুন।',
      durationMs: 3000,
      pauseAfterMs: 0,
      actions: [{ type: 'SHOW_CRYSTAL' }],
      accessibilitySummaryEn: 'A grid of alternating red and blue particles is shown.',
      accessibilitySummaryBn: 'লাল এবং নীল কণার পর্যায়ক্রমিক একটি গ্রিড দেখানো হয়েছে।'
    },
    {
      id: 'step-2-measure-ab',
      titleEn: 'Measuring Property Along Direction AB',
      titleBn: 'AB দিক বরাবর ধর্ম পরিমাপ',
      narrationEn: 'Let us measure a physical property, like electrical resistance or refractive index, along direction A-B.',
      narrationBn: 'ধরা যাক আমরা বৈদ্যুতিক রোধ বা প্রতিসরাঙ্কের মতো একটি ভৌত ধর্ম A-B দিক বরাবর পরিমাপ করছি।',
      whatHappenedEn: 'A laser probe swept along the horizontal direction A-B.',
      whatHappenedBn: 'একটি লেজার প্রোব অনুভূমিক A-B দিক বরাবর প্রবাহিত হয়েছে।',
      whyItHappenedEn: 'Along A-B, the probe encounters alternating red and blue particles (Red, Blue, Red, Blue).',
      whyItHappenedBn: 'A-B দিক বরাবর, প্রোবটি পর্যায়ক্রমে লাল এবং নীল কণার সম্মুখীন হয় (লাল, নীল, লাল, নীল)।',
      observeEn: 'Look at the sequence of particles the line passes through.',
      observeBn: 'রেখাটি যে কণাগুলির মধ্য দিয়ে যায় তাদের ক্রমটি দেখুন।',
      durationMs: 4000,
      pauseAfterMs: 0,
      actions: [{ type: 'PROBE_AB' }],
      accessibilitySummaryEn: 'A horizontal line sweeps across alternating colored particles.',
      accessibilitySummaryBn: 'একটি অনুভূমিক রেখা বিভিন্ন রঙের কণাগুলির মধ্য দিয়ে যায়।'
    },
    {
      id: 'step-3-measure-cd',
      titleEn: 'Measuring Property Along Direction CD',
      titleBn: 'CD দিক বরাবর ধর্ম পরিমাপ',
      narrationEn: 'Now, let us measure the same property along a diagonal direction, C-D.',
      narrationBn: 'এখন, আমরা একটি তির্যক দিক C-D বরাবর একই ধর্ম পরিমাপ করি।',
      whatHappenedEn: 'The probe swept along the diagonal direction C-D.',
      whatHappenedBn: 'প্রোবটি তির্যক C-D দিক বরাবর প্রবাহিত হয়েছে।',
      whyItHappenedEn: 'Along C-D, the probe encounters only one type of particle (e.g., only Blue).',
      whyItHappenedBn: 'C-D দিক বরাবর, প্রোবটি কেবল এক ধরনের কণার (যেমন, শুধুমাত্র নীল) সম্মুখীন হয়।',
      observeEn: 'Notice that the particle sequence is completely different from direction A-B.',
      observeBn: 'লক্ষ্য করুন যে কণাগুলির ক্রম A-B দিকের থেকে সম্পূর্ণ ভিন্ন।',
      durationMs: 4000,
      pauseAfterMs: 0,
      actions: [{ type: 'PROBE_CD' }],
      accessibilitySummaryEn: 'A diagonal line sweeps across only blue particles.',
      accessibilitySummaryBn: 'একটি তির্যক রেখা কেবল নীল কণাগুলির মধ্য দিয়ে যায়।'
    },
    {
      id: 'step-4-anisotropy-conclusion',
      titleEn: 'Anisotropy in Crystals',
      titleBn: 'স্ফটিকে অসমদিকতা',
      narrationEn: 'Since the arrangement of particles is different along different directions, the physical property will have different values. This is Anisotropy.',
      narrationBn: 'যেহেতু বিভিন্ন দিক বরাবর কণাগুলির বিন্যাস ভিন্ন, তাই ভৌত ধর্মের মানও ভিন্ন হবে। একেই অসমদিকতা বলে।',
      whatHappenedEn: 'Both directions A-B and C-D are highlighted to show the contrast.',
      whatHappenedBn: 'বৈসাদৃশ্য দেখানোর জন্য A-B এবং C-D উভয় দিকই উজ্জ্বল করা হয়েছে।',
      whyItHappenedEn: 'Crystals are anisotropic because their strict long-range order creates specific repeating patterns that vary by angle.',
      whyItHappenedBn: 'স্ফটিকগুলি অসমদিকধর্মী কারণ তাদের কঠোর দীর্ঘ-পাল্লার শৃঙ্খলা নির্দিষ্ট পর্যায়বৃত্ত বিন্যাস তৈরি করে যা কোণ অনুসারে পরিবর্তিত হয়।',
      observeEn: 'Compare the environments along both paths.',
      observeBn: 'উভয় পথ বরাবর পরিবেশের তুলনা করুন।',
      durationMs: 3000,
      pauseAfterMs: 0,
      actions: [{ type: 'COMPARE_BOTH' }],
      checkpoint: {
        promptEn: 'Does a crystalline solid generally exhibit anisotropy or isotropy?',
        promptBn: 'একটি স্ফটিকাকার কঠিন সাধারণত অসমদিকতা নাকি সমদিকতা প্রদর্শন করে?',
        expectedResponse: 'anisotropy',
        hintEn: 'Remember that different directions yield different properties because of the ordered arrangement.',
        hintBn: 'মনে রাখবেন সুশৃঙ্খল বিন্যাসের কারণে বিভিন্ন দিকে ভিন্ন ভিন্ন ধর্ম পাওয়া যায়।'
      },
      accessibilitySummaryEn: 'Both horizontal and diagonal lines are shown simultaneously for comparison.',
      accessibilitySummaryBn: 'তুলনার জন্য অনুভূমিক এবং তির্যক উভয় রেখাই একসাথে দেখানো হয়েছে।'
    },
    {
      id: 'step-5-isotropy',
      titleEn: 'Isotropy in Amorphous Solids',
      titleBn: 'অস্ফটিকাকার কঠিনে সমদিকতা',
      narrationEn: 'In amorphous solids, particles are arranged randomly. The average arrangement is the same in all directions. Thus, properties are identical in all directions (Isotropy).',
      narrationBn: 'অস্ফটিকাকার কঠিনে কণাগুলি এলোমেলোভাবে বিন্যস্ত থাকে। সমস্ত দিক বরাবর গড় বিন্যাস একই থাকে। তাই, সমস্ত দিকে ধর্মগুলি অভিন্ন হয় (সমদিকতা)।',
      whatHappenedEn: 'The lattice melted into a disordered state. The probe lines now encounter a random, statistically similar mix in any direction.',
      whatHappenedBn: 'জালকটি গলে একটি বিশৃঙ্খল অবস্থায় পরিণত হয়েছে। প্রোব রেখাগুলি এখন যেকোনো দিকে একটি এলোমেলো কিন্তু পরিসংখ্যানগতভাবে অনুরূপ মিশ্রণের সম্মুখীন হয়।',
      whyItHappenedEn: 'Without long-range order, no specific direction is unique. Averaged over macroscopic distances, the material is uniform.',
      whyItHappenedBn: 'দীর্ঘ-পাল্লার শৃঙ্খলা না থাকলে, কোনো নির্দিষ্ট দিক অনন্য হয় না। বৃহৎ পরিসরে গড় করলে, উপাদানটি সর্বত্র অভিন্ন বলে প্রতীয়মান হয়।',
      observeEn: 'Notice the lack of distinct paths in the disordered state.',
      observeBn: 'বিশৃঙ্খল অবস্থায় নির্দিষ্ট পথের অভাব লক্ষ্য করুন।',
      durationMs: 4000,
      pauseAfterMs: 0,
      actions: [{ type: 'SHOW_ISOTROPY' }],
      accessibilitySummaryEn: 'Particles become randomized, and probes sweep in multiple directions showing identical random averages.',
      accessibilitySummaryBn: 'কণাগুলি এলোমেলো হয়ে যায় এবং বিভিন্ন দিকে প্রোব প্রবাহিত হয়ে অভিন্ন গড় মান দেখায়।'
    }
  ]
};
