import type { GuidedLessonSequence } from '../engine/GuidedLessonTypes';

export const crystallineAmorphousData: GuidedLessonSequence = {
  id: 'crystalline-amorphous',
  titleEn: 'Crystalline vs Amorphous Solids',
  titleBn: 'স্ফটিকাকার বনাম অস্ফটিকাকার কঠিন',
  steps: [
    {
      id: 'step-1-liquid',
      titleEn: 'Starting from the Melt',
      titleBn: 'গলিত অবস্থা থেকে শুরু',
      narrationEn: 'Both solids start as liquids where particles are disordered and mobile.',
      narrationBn: 'উভয় কঠিন পদার্থই তরল অবস্থা থেকে শুরু হয় যেখানে কণাগুলি বিশৃঙ্খল এবং সচল থাকে।',
      whatHappenedEn: 'We see two identical samples of a liquid substance.',
      whatHappenedBn: 'আমরা একটি তরল পদার্থের দুটি অভিন্ন নমুনা দেখতে পাচ্ছি।',
      whyItHappenedEn: 'At high temperatures, thermal energy disrupts any ordered arrangement.',
      whyItHappenedBn: 'উচ্চ তাপমাত্রায় তাপীয় শক্তি যেকোনো শৃঙ্খলিত বিন্যাসকে ভেঙে দেয়।',
      observeEn: 'Observe the random movement of particles in both chambers.',
      observeBn: 'উভয় প্রকোষ্ঠে কণাগুলির এলোমেলো চলন লক্ষ্য করুন।',
      durationMs: 3000,
      pauseAfterMs: 0,
      actions: [{ type: 'STATE_LIQUID' }],
      accessibilitySummaryEn: 'Two containers showing moving liquid particles.',
      accessibilitySummaryBn: 'দুটি পাত্রে চলমান তরল কণা দেখানো হয়েছে।'
    },
    {
      id: 'step-2-cooling-crystalline',
      titleEn: 'Slow Cooling (Crystalline Growth)',
      titleBn: 'ধীর শীতলীকরণ (স্ফটিকাকার গঠন)',
      narrationEn: 'If cooled slowly, particles have time to arrange into a regular, repeating pattern.',
      narrationBn: 'যদি ধীরে ধীরে শীতল করা হয়, তবে কণাগুলি একটি নিয়মিত, পুনরাবৃত্ত বিন্যাসে সজ্জিত হওয়ার সময় পায়।',
      whatHappenedEn: 'The left sample was cooled slowly, forming a highly ordered crystal lattice.',
      whatHappenedBn: 'বাম দিকের নমুনাটি ধীরে ধীরে শীতল করা হয়েছে, যা একটি অত্যন্ত সুশৃঙ্খল স্ফটিক জালক তৈরি করেছে।',
      whyItHappenedEn: 'Slow cooling gives particles sufficient time to minimize their potential energy by locking into the most stable periodic arrangement.',
      whyItHappenedBn: 'ধীর শীতলীকরণ কণাগুলিকে সবচেয়ে স্থিতিশীল পর্যায়বৃত্ত বিন্যাসে আবদ্ধ হয়ে তাদের স্থিতি শক্তি কমানোর জন্য পর্যাপ্ত সময় দেয়।',
      observeEn: 'Notice the long-range order on the left.',
      observeBn: 'বাম দিকের দীর্ঘ-পাল্লার শৃঙ্খলাটি লক্ষ্য করুন।',
      durationMs: 4000,
      pauseAfterMs: 0,
      actions: [{ type: 'COOL_CRYSTALLINE' }],
      accessibilitySummaryEn: 'Left container particles form a neat grid.',
      accessibilitySummaryBn: 'বাম দিকের পাত্রের কণাগুলি একটি পরিপাটি গ্রিড তৈরি করে।'
    },
    {
      id: 'step-3-cooling-amorphous',
      titleEn: 'Rapid Cooling (Amorphous Solid)',
      titleBn: 'দ্রুত শীতলীকরণ (অস্ফটিকাকার কঠিন)',
      narrationEn: 'If cooled rapidly, particles are frozen in their disordered positions before they can arrange themselves.',
      narrationBn: 'যদি দ্রুত শীতল করা হয়, তবে কণাগুলি নিজেদের সজ্জিত করার আগেই তাদের বিশৃঙ্খল অবস্থানে জমে যায়।',
      whatHappenedEn: 'The right sample was quenched (cooled quickly), forming an amorphous solid.',
      whatHappenedBn: 'ডান দিকের নমুনাটি দ্রুত শীতল করা হয়েছে, যা একটি অস্ফটিকাকার কঠিন তৈরি করেছে।',
      whyItHappenedEn: 'The rapid drop in temperature removes kinetic energy too fast for the particles to find their optimal crystal positions.',
      whyItHappenedBn: 'তাপমাত্রার দ্রুত পতন কণাগুলির গতিশক্তি এত দ্রুত হ্রাস করে যে তারা তাদের সর্বোত্তম স্ফটিক অবস্থান খুঁজে পাওয়ার সময় পায় না।',
      observeEn: 'Notice that it is solid (fixed), but lacks long-range order.',
      observeBn: 'লক্ষ্য করুন যে এটি কঠিন (স্থির), কিন্তু এতে দীর্ঘ-পাল্লার শৃঙ্খলা নেই।',
      durationMs: 4000,
      pauseAfterMs: 0,
      actions: [{ type: 'COOL_AMORPHOUS' }],
      checkpoint: {
        promptEn: 'Which cooling process generally produces an amorphous solid (like glass)?',
        promptBn: 'কোন শীতলীকরণ প্রক্রিয়া সাধারণত (কাঁচের মতো) অস্ফটিকাকার কঠিন পদার্থ তৈরি করে?',
        expectedResponse: 'rapid',
        hintEn: 'Think about whether particles need more or less time to form a neat pattern.',
        hintBn: 'ভেবে দেখুন একটি পরিপাটি বিন্যাস তৈরি করতে কণাগুলির বেশি না কম সময় প্রয়োজন।'
      },
      accessibilitySummaryEn: 'Right container particles freeze in a random pattern.',
      accessibilitySummaryBn: 'ডান দিকের পাত্রের কণাগুলি একটি এলোমেলো বিন্যাসে জমে যায়।'
    },
    {
      id: 'step-4-cleavage',
      titleEn: 'Cleavage Property',
      titleBn: 'ভাঙনের ধর্ম',
      narrationEn: 'When cut with a sharp edge, crystalline solids split into smooth planes, while amorphous solids break with irregular surfaces.',
      narrationBn: 'তীক্ষ্ণ ধারালো বস্তু দিয়ে কাটলে স্ফটিকাকার কঠিন মসৃণ তলে বিভক্ত হয়, অন্যদিকে অস্ফটিকাকার কঠিন অনিয়মিত তলে ভাঙে।',
      whatHappenedEn: 'Both solids were subjected to a fracturing force.',
      whatHappenedBn: 'উভয় কঠিন পদার্থের উপর ভাঙন বল প্রয়োগ করা হয়েছে।',
      whyItHappenedEn: 'Crystalline solids cleave along distinct crystallographic planes. Amorphous solids have no such planes, causing conchoidal (curved/irregular) fracture.',
      whyItHappenedBn: 'স্ফটিকাকার কঠিন নির্দিষ্ট তলের সাপেক্ষে ভাঙে। অস্ফটিকাকার কঠিনে এমন কোনো তল না থাকায় এরা বক্র বা অনিয়মিতভাবে ভাঙে।',
      observeEn: 'Look at the straight cut on the left vs the jagged break on the right.',
      observeBn: 'বাম দিকের সোজা কাট এবং ডান দিকের এবড়োখেবড়ো ভাঙন লক্ষ্য করুন।',
      durationMs: 4000,
      pauseAfterMs: 0,
      actions: [{ type: 'SHOW_CLEAVAGE' }],
      accessibilitySummaryEn: 'The ordered solid breaks cleanly in half. The disordered one breaks in a jagged line.',
      accessibilitySummaryBn: 'সুশৃঙ্খল কঠিনটি পরিষ্কারভাবে দুভাগে ভেঙে যায়। বিশৃঙ্খলটি এবড়োখেবড়ো রেখায় ভাঙে।'
    },
    {
      id: 'step-5-melting',
      titleEn: 'Melting Point Characteristics',
      titleBn: 'গলনাঙ্কের বৈশিষ্ট্য',
      narrationEn: 'Crystalline solids have a sharp melting point. Amorphous solids soften over a range of temperatures.',
      narrationBn: 'স্ফটিকাকার কঠিনের একটি সুনির্দিষ্ট গলনাঙ্ক থাকে। অস্ফটিকাকার কঠিন একটি নির্দিষ্ট তাপমাত্রার পরিসরে ধীরে ধীরে নরম হয়।',
      whatHappenedEn: 'Heat is applied. The amorphous solid softens gradually, while the crystalline solid melts suddenly at a specific temperature.',
      whatHappenedBn: 'তাপ প্রয়োগ করা হয়েছে। অস্ফটিকাকার কঠিন ধীরে ধীরে নরম হয়, অন্যদিকে স্ফটিকাকার কঠিন একটি নির্দিষ্ট তাপমাত্রায় হঠাৎ গলে যায়।',
      whyItHappenedEn: 'In a crystal, all identical bonds break at the same thermal energy. In amorphous solids, varying bond strengths break at different temperatures.',
      whyItHappenedBn: 'স্ফটিকে সমস্ত অভিন্ন বন্ধন একই তাপীয় শক্তিতে ভাঙে। অস্ফটিকাকার কঠিনে বিভিন্ন শক্তির বন্ধনগুলি ভিন্ন ভিন্ন তাপমাত্রায় ভাঙে।',
      observeEn: 'Notice how the right side begins to flow earlier and gradually.',
      observeBn: 'লক্ষ্য করুন কীভাবে ডান দিকটি আগে এবং ধীরে ধীরে প্রবাহিত হতে শুরু করে।',
      durationMs: 5000,
      pauseAfterMs: 0,
      actions: [{ type: 'SHOW_MELTING' }],
      accessibilitySummaryEn: 'The amorphous solid softens and melts gradually. The crystalline solid melts instantly at a threshold.',
      accessibilitySummaryBn: 'অস্ফটিকাকার কঠিন ধীরে ধীরে নরম হয় এবং গলে যায়। স্ফটিকাকার কঠিন নির্দিষ্ট সীমায় পৌঁছানো মাত্র গলে যায়।'
    }
  ]
};
