import type { GuidedLessonSequence } from '../engine/GuidedLessonTypes';

export const generalCharacteristicsData: GuidedLessonSequence = {
  id: 'general-characteristics',
  titleEn: 'General Characteristics of Solid State',
  titleBn: 'কঠিন অবস্থার সাধারণ বৈশিষ্ট্য',
  steps: [
    {
      id: 'step-1-mass-shape-volume',
      titleEn: 'Definite Mass, Volume, and Shape',
      titleBn: 'নির্দিষ্ট ভর, আয়তন এবং আকার',
      narrationEn: 'Solids have a definite mass, volume, and shape regardless of the container they are placed in.',
      narrationBn: 'কঠিন পদার্থকে যে পাত্রেই রাখা হোক না কেন, তাদের একটি নির্দিষ্ট ভর, আয়তন এবং আকার থাকে।',
      whatHappenedEn: 'A solid block was moved between different containers without changing its shape.',
      whatHappenedBn: 'একটি কঠিন খণ্ডকে বিভিন্ন পাত্রে স্থানান্তরিত করা হয়েছে, কিন্তু তার আকারের কোনো পরিবর্তন হয়নি।',
      whyItHappenedEn: 'Strong intermolecular forces hold the constituent particles in fixed positions, preventing them from flowing.',
      whyItHappenedBn: 'শক্তিশালী আন্তঃআণবিক বল গঠনকারী কণাগুলিকে নির্দিষ্ট অবস্থানে ধরে রাখে, যার ফলে তারা প্রবাহিত হতে পারে না।',
      observeEn: 'Observe how the solid maintains its own shape, unlike liquids.',
      observeBn: 'লক্ষ্য করুন তরলের মতো নয়, কঠিন পদার্থ কীভাবে নিজের আকার বজায় রাখে।',
      durationMs: 3000,
      pauseAfterMs: 0,
      actions: [{ type: 'SHOW_SHAPE' }],
      accessibilitySummaryEn: 'A solid cube maintains its shape when dropped into a bowl.',
      accessibilitySummaryBn: 'একটি কঠিন ঘনক বাটিতে ফেলার পরেও নিজের আকার বজায় রাখে।'
    },
    {
      id: 'step-2-short-distance',
      titleEn: 'Short Intermolecular Distances',
      titleBn: 'ক্ষুদ্র আন্তঃআণবিক দূরত্ব',
      narrationEn: 'The distance between adjacent constituent particles (atoms, ions, or molecules) is very short.',
      narrationBn: 'সন্নিহিত গঠনকারী কণাগুলির (পরমাণু, আয়ন বা অণু) মধ্যবর্তী দূরত্ব খুবই ক্ষুদ্র হয়।',
      whatHappenedEn: 'The camera zoomed in to show particles packed tightly against each other.',
      whatHappenedBn: 'ক্যামেরা জুম করে দেখানো হয়েছে কণাগুলি একে অপরের সাথে কতটা ঘনিষ্ঠভাবে প্যাক করা আছে।',
      whyItHappenedEn: 'The attractive forces are strong enough to overcome thermal energy, pulling particles close until electron clouds repel.',
      whyItHappenedBn: 'আকর্ষণ বল তাপীয় শক্তিকে অতিক্রম করার জন্য যথেষ্ট শক্তিশালী, যা কণাগুলিকে কাছে টানে যতক্ষণ না ইলেকট্রন মেঘ বিকর্ষণ করে।',
      observeEn: 'Notice the lack of significant empty space between the particles.',
      observeBn: 'কণাগুলির মধ্যে উল্লেখযোগ্য ফাঁকা জায়গার অভাব লক্ষ্য করুন।',
      durationMs: 3000,
      pauseAfterMs: 0,
      actions: [{ type: 'SHOW_DISTANCE' }],
      accessibilitySummaryEn: 'Zoomed view showing particles densely packed together.',
      accessibilitySummaryBn: 'কণাগুলি একে অপরের সাথে কতটা ঘনিষ্ঠভাবে প্যাক করা আছে তা দেখানো হয়েছে।'
    },
    {
      id: 'step-3-strong-forces',
      titleEn: 'Strong Intermolecular Forces',
      titleBn: 'শক্তিশালী আন্তঃআণবিক বল',
      narrationEn: 'The intermolecular forces holding the particles together are very strong.',
      narrationBn: 'কণাগুলিকে একত্রে ধরে রাখা আন্তঃআণবিক বলগুলি অত্যন্ত শক্তিশালী হয়।',
      whatHappenedEn: 'Lines representing strong attractive forces appeared between the particles.',
      whatHappenedBn: 'কণাগুলির মধ্যে শক্তিশালী আকর্ষণ বল নির্দেশকারী রেখাগুলি দৃশ্যমান হয়েছে।',
      whyItHappenedEn: 'These strong bonds are the fundamental reason solids are rigid and have high melting points compared to other states.',
      whyItHappenedBn: 'এই শক্তিশালী বন্ধনগুলিই প্রধান কারণ যার জন্য কঠিন পদার্থ দৃঢ় হয় এবং অন্যান্য অবস্থার তুলনায় এদের গলনাঙ্ক উচ্চ হয়।',
      observeEn: 'See the interconnected network of forces keeping the structure stable.',
      observeBn: 'কাঠামোটিকে স্থিতিশীল রাখা বলগুলির আন্তঃসংযুক্ত নেটওয়ার্ক দেখুন।',
      durationMs: 3000,
      pauseAfterMs: 0,
      actions: [{ type: 'SHOW_FORCES' }],
      accessibilitySummaryEn: 'Glowing bonds appear between the close-packed particles.',
      accessibilitySummaryBn: 'কাছাকাছি থাকা কণাগুলির মধ্যে উজ্জ্বল বন্ধনগুলি উপস্থিত হয়েছে।'
    },
    {
      id: 'step-4-incompressible',
      titleEn: 'Incompressible and Rigid',
      titleBn: 'অসংকোচনশীল এবং অনমনীয়',
      narrationEn: 'Solids are generally incompressible and rigid. They resist changes to their shape.',
      narrationBn: 'কঠিন পদার্থ সাধারণত অসংকোচনশীল এবং অনমনীয় হয়। তারা তাদের আকারের পরিবর্তন প্রতিরোধ করে।',
      whatHappenedEn: 'A heavy weight was placed on the solid, but it did not compress.',
      whatHappenedBn: 'কঠিন পদার্থের উপর একটি ভারী ওজন রাখা হয়েছে, কিন্তু এটি সংকুচিত হয়নি।',
      whyItHappenedEn: 'Because intermolecular distances are already minimal, pushing particles closer causes strong electron-electron repulsion.',
      whyItHappenedBn: 'যেহেতু আন্তঃআণবিক দূরত্ব আগে থেকেই ন্যূনতম, কণাগুলিকে আরও কাছাকাছি ঠেলে দিলে তীব্র ইলেকট্রন-ইলেকট্রন বিকর্ষণ ঘটে।',
      observeEn: 'Notice how the solid pushes back against the applied force without shrinking.',
      observeBn: 'লক্ষ্য করুন কীভাবে কঠিন পদার্থটি সংকুচিত না হয়ে প্রযুক্ত বলের বিরুদ্ধে প্রতিরোধ গড়ে তোলে।',
      durationMs: 4000,
      pauseAfterMs: 0,
      actions: [{ type: 'SHOW_INCOMPRESSIBLE' }],
      checkpoint: {
        promptEn: 'Why are solids practically incompressible?',
        promptBn: 'কঠিন পদার্থগুলি কার্যত অসংকোচনশীল কেন?',
        expectedResponse: 'Intermolecular distances are already minimal',
        hintEn: 'Think about what happens when electron clouds of closely packed atoms are forced even closer.',
        hintBn: 'ভেবে দেখুন ঘনিষ্ঠভাবে প্যাক করা পরমাণুগুলির ইলেকট্রন মেঘগুলিকে আরও কাছাকাছি নিয়ে আসলে কী ঘটে।'
      },
      accessibilitySummaryEn: 'A piston tries to crush the solid but fails to compress it.',
      accessibilitySummaryBn: 'একটি পিস্টন কঠিন পদার্থটিকে সংকুচিত করার চেষ্টা করে কিন্তু ব্যর্থ হয়।'
    },
    {
      id: 'step-5-fixed-positions',
      titleEn: 'Fixed Positions but Vibrational Motion',
      titleBn: 'নির্দিষ্ট অবস্থান কিন্তু কম্পনশীল গতি',
      narrationEn: 'Constituent particles have fixed positions but can still oscillate about their mean positions.',
      narrationBn: 'গঠনকারী কণাগুলির অবস্থান নির্দিষ্ট, তবে তারা এখনও তাদের সাম্যাবস্থানের চারপাশে কম্পন করতে পারে।',
      whatHappenedEn: 'The static model animated to show continuous small vibrations.',
      whatHappenedBn: 'স্থির মডেলটি এখন ক্রমাগত ছোট কম্পন প্রদর্শন করছে।',
      whyItHappenedEn: 'Thermal energy at any temperature above absolute zero causes the particles to vibrate in their potential wells.',
      whyItHappenedBn: 'পরম শূন্যের উপরের যেকোনো তাপমাত্রায় তাপীয় শক্তির কারণে কণাগুলি তাদের পটেনশিয়াল ওয়েলের মধ্যে কম্পন করে।',
      observeEn: 'The particles jiggle but do not leave their designated spots in the lattice.',
      observeBn: 'কণাগুলি কাঁপছে কিন্তু জালকে তাদের নির্ধারিত স্থান ত্যাগ করছে না।',
      durationMs: 3000,
      pauseAfterMs: 0,
      actions: [{ type: 'SHOW_VIBRATION' }],
      accessibilitySummaryEn: 'Particles vibrate rapidly in place without moving around.',
      accessibilitySummaryBn: 'কণাগুলি দ্রুত নিজেদের স্থানে কম্পন করছে কিন্তু স্থানান্তরিত হচ্ছে না।'
    }
  ]
};
