import type { GuidedLessonSequence } from '../engine/GuidedLessonTypes';

export const latticeToUnitCellData: GuidedLessonSequence = {
  id: 'lattice-to-unit-cell',
  titleEn: 'Lattice, Lattice Point, and Unit Cell',
  titleBn: 'জালক, জালক বিন্দু এবং একক কোষ',
  steps: [
    {
      id: 'step-1-real-crystal',
      titleEn: 'The Real Crystal',
      titleBn: 'প্রকৃত স্ফটিক',
      narrationEn: 'A real crystal is made of closely packed atoms, molecules, or ions.',
      narrationBn: 'একটি প্রকৃত স্ফটিক ঘনিষ্ঠভাবে প্যাক করা পরমাণু, অণু বা আয়ন দ্বারা গঠিত।',
      whatHappenedEn: 'A 3D block of identical atoms appeared.',
      whatHappenedBn: 'অভিন্ন পরমাণুর একটি ত্রিমাত্রিক ব্লক দৃশ্যমান হয়েছে।',
      whyItHappenedEn: 'This represents the physical reality of a crystalline solid.',
      whyItHappenedBn: 'এটি একটি স্ফটিকাকার কঠিনের ভৌত বাস্তবতাকে উপস্থাপন করে।',
      observeEn: 'Notice how dense and crowded the actual atomic arrangement is.',
      observeBn: 'প্রকৃত পারমাণবিক বিন্যাস কতটা ঘন তা লক্ষ্য করুন।',
      durationMs: 3000,
      pauseAfterMs: 0,
      actions: [{ type: 'SHOW_ATOMS' }],
      accessibilitySummaryEn: 'A dense 3D cube of solid spheres representing atoms.',
      accessibilitySummaryBn: 'পরমাণু নির্দেশকারী কঠিন গোলকের একটি ঘন ত্রিমাত্রিক ঘনক।'
    },
    {
      id: 'step-2-lattice-points',
      titleEn: 'Abstraction to Lattice Points',
      titleBn: 'জালক বিন্দুতে বিমূর্তকরণ',
      narrationEn: 'To study the geometry, we replace each repeating structural unit with a geometrical point, called a Lattice Point.',
      narrationBn: 'জ্যামিতি অধ্যয়নের জন্য, আমরা প্রতিটি পুনরাবৃত্ত কাঠামোগত একককে একটি জ্যামিতিক বিন্দু দিয়ে প্রতিস্থাপন করি, যাকে জালক বিন্দু বলা হয়।',
      whatHappenedEn: 'The bulky atoms shrank down to infinitesimally small geometrical points.',
      whatHappenedBn: 'বিশাল পরমাণুগুলি সংকুচিত হয়ে ক্ষুদ্র জ্যামিতিক বিন্দুতে পরিণত হয়েছে।',
      whyItHappenedEn: 'This removes the complexity of the actual atomic shapes and leaves only the mathematical framework.',
      whyItHappenedBn: 'এটি প্রকৃত পারমাণবিক আকারের জটিলতা দূর করে এবং কেবল গাণিতিক কাঠামোটিকে অবশিষ্ট রাখে।',
      observeEn: 'Observe that the spatial arrangement remains exactly the same.',
      observeBn: 'লক্ষ্য করুন যে স্থানিক বিন্যাসটি হুবহু একই আছে।',
      durationMs: 4000,
      pauseAfterMs: 0,
      actions: [{ type: 'SHRINK_TO_POINTS' }],
      accessibilitySummaryEn: 'The large spheres shrink into tiny glowing dots in the exact same positions.',
      accessibilitySummaryBn: 'বড় গোলকগুলি ঠিক একই অবস্থানে সংকুচিত হয়ে ছোট উজ্জ্বল বিন্দুতে পরিণত হয়।'
    },
    {
      id: 'step-3-space-lattice',
      titleEn: 'The Crystal Lattice (Space Lattice)',
      titleBn: 'স্ফটিক জালক (স্থানিক জালক)',
      narrationEn: 'The regular, three-dimensional array of these points is called the Crystal Lattice or Space Lattice.',
      narrationBn: 'এই বিন্দুগুলির নিয়মিত, ত্রিমাত্রিক বিন্যাসকে স্ফটিক জালক বা স্থানিক জালক বলা হয়।',
      whatHappenedEn: 'Grid lines connected the lattice points, forming a visible 3D scaffolding.',
      whatHappenedBn: 'গ্রিড রেখাগুলি জালক বিন্দুগুলিকে সংযুক্ত করে একটি দৃশ্যমান ত্রিমাত্রিক কাঠামো তৈরি করেছে।',
      whyItHappenedEn: 'Connecting the points helps us visualize the periodic translational symmetry of the crystal.',
      whyItHappenedBn: 'বিন্দুগুলিকে সংযুক্ত করা স্ফটিকের পর্যায়বৃত্ত সমমিতি কল্পনা করতে সাহায্য করে।',
      observeEn: 'See how the entire structure is built from repeating identical geometric blocks.',
      observeBn: 'দেখুন কীভাবে সম্পূর্ণ কাঠামোটি অভিন্ন জ্যামিতিক ব্লকের পুনরাবৃত্তি থেকে তৈরি হয়েছে।',
      durationMs: 4000,
      pauseAfterMs: 0,
      actions: [{ type: 'SHOW_LATTICE_LINES' }],
      accessibilitySummaryEn: 'Lines draw between the dots to form a 3D grid or scaffolding.',
      accessibilitySummaryBn: 'বিন্দুগুলির মধ্যে রেখা টানা হয় যা একটি ত্রিমাত্রিক গ্রিড বা কাঠামো তৈরি করে।'
    },
    {
      id: 'step-4-unit-cell',
      titleEn: 'Identifying the Unit Cell',
      titleBn: 'একক কোষ চিহ্নিতকরণ',
      narrationEn: 'The smallest repeating 3D unit of this lattice, which generates the entire crystal by repetition, is the Unit Cell.',
      narrationBn: 'এই জালকের ক্ষুদ্রতম পুনরাবৃত্ত ত্রিমাত্রিক একক, যার পুনরাবৃত্তির মাধ্যমে সম্পূর্ণ স্ফটিক তৈরি হয়, তাকে একক কোষ বলে।',
      whatHappenedEn: 'One single structural block (eight points forming a small cube) was highlighted, while the rest faded.',
      whatHappenedBn: 'একটি মাত্র কাঠামোগত ব্লক (আটটি বিন্দু মিলে একটি ছোট ঘনক) উজ্জ্বল করা হয়েছে এবং বাকিগুলি ম্লান হয়ে গেছে।',
      whyItHappenedEn: 'This small block contains all the symmetry and structural information of the macroscopic crystal.',
      whyItHappenedBn: 'এই ছোট ব্লকটিতে ম্যাক্রোস্কোপিক স্ফটিকের সমস্ত সমমিতি এবং কাঠামোগত তথ্য রয়েছে।',
      observeEn: 'Notice that repeating this single block in all directions would rebuild the whole lattice.',
      observeBn: 'লক্ষ্য করুন যে এই একটি ব্লকের সমস্ত দিকে পুনরাবৃত্তি করলে সম্পূর্ণ জালকটি পুনর্গঠিত হবে।',
      durationMs: 4000,
      pauseAfterMs: 0,
      actions: [{ type: 'HIGHLIGHT_UNIT_CELL' }],
      checkpoint: {
        promptEn: 'What is the relationship between a Lattice Point and the Unit Cell?',
        promptBn: 'জালক বিন্দু এবং একক কোষের মধ্যে সম্পর্ক কী?',
        expectedResponse: 'Lattice points define the corners (or positions) of the unit cell',
        hintEn: 'Look at the highlighted unit cell. What sits at its corners?',
        hintBn: 'উজ্জ্বল করা একক কোষটির দিকে তাকান। এর কোণায় কী বসে আছে?'
      },
      accessibilitySummaryEn: 'One small 8-dot cube in the corner of the lattice lights up brightly.',
      accessibilitySummaryBn: 'জালকের কোণায় একটি ছোট ৮-বিন্দুর ঘনক উজ্জ্বল হয়ে ওঠে।'
    },
    {
      id: 'step-5-rebuild',
      titleEn: 'Translational Symmetry',
      titleBn: 'স্থানান্তরণ সমমিতি',
      narrationEn: 'By translating (moving) the unit cell along its edges, we can generate the entire space lattice.',
      narrationBn: 'একক কোষটিকে তার প্রান্ত বরাবর স্থানান্তরিত (সরিয়ে) করে আমরা সম্পূর্ণ স্থানিক জালক তৈরি করতে পারি।',
      whatHappenedEn: 'The single unit cell duplicated itself in X, Y, and Z directions, rebuilding the large lattice.',
      whatHappenedBn: 'একক কোষটি X, Y এবং Z দিকে নিজেকে প্রতিলিপি করে বড় জালকটি পুনর্গঠিত করেছে।',
      whyItHappenedEn: 'This demonstrates the fundamental property of crystals: they are perfectly periodic and repeating in 3D space.',
      whyItHappenedBn: 'এটি স্ফটিকের মৌলিক বৈশিষ্ট্য প্রদর্শন করে: তারা ত্রিমাত্রিক স্থানে নিখুঁতভাবে পর্যায়বৃত্ত এবং পুনরাবৃত্ত হয়।',
      observeEn: 'Watch how the macroscopic crystal grows from the microscopic unit cell.',
      observeBn: 'মাইক্রোস্কোপিক একক কোষ থেকে কীভাবে ম্যাক্রোস্কোপিক স্ফটিক বৃদ্ধি পায় তা দেখুন।',
      durationMs: 5000,
      pauseAfterMs: 0,
      actions: [{ type: 'REBUILD_LATTICE' }],
      accessibilitySummaryEn: 'The single highlighted cube duplicates to fill out the original large grid.',
      accessibilitySummaryBn: 'একক উজ্জ্বল ঘনকটি মূল বড় গ্রিডটি পূরণ করার জন্য প্রতিলিপি তৈরি করে।'
    }
  ]
};
