import { BilingualText } from '../../BilingualText';
import { ArrowRight, Box, Grid, Layers, Droplet } from 'lucide-react';

export const ConceptMap = () => {
  return (
    <div className="w-full bg-slate-50 dark:bg-slate-900 rounded-xl p-8 border border-slate-200 dark:border-slate-800 shadow-sm mt-6">
      <h3 className="text-xl font-bold text-slate-800 dark:text-slate-100 mb-8 text-center">
        <BilingualText en="Solid State Chemistry Concept Map" bn="কঠিন অবস্থার রসায়ন - ধারণা মানচিত্র" />
      </h3>
      
      <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
        {/* Column 1 */}
        <div className="flex flex-col gap-4">
          <div className="bg-indigo-100 dark:bg-indigo-900/50 p-4 rounded-lg border border-indigo-200 dark:border-indigo-800 text-center relative">
            <Layers className="w-8 h-8 text-indigo-600 dark:text-indigo-400 mx-auto mb-2" />
            <h4 className="font-bold text-indigo-900 dark:text-indigo-100 text-sm">
              <BilingualText en="Matter" bn="পদার্থ" />
            </h4>
            <div className="hidden md:block absolute -right-6 top-1/2 -translate-y-1/2">
              <ArrowRight className="w-4 h-4 text-slate-400" />
            </div>
          </div>
          <div className="flex-1 bg-white dark:bg-slate-800 p-3 rounded-lg text-xs text-slate-600 dark:text-slate-300 border border-slate-200 dark:border-slate-700">
            <BilingualText en="Solid State is defined by strong intermolecular forces, definite shape and volume, and rigidity." bn="কঠিন অবস্থা শক্তিশালী আন্তঃআণবিক বল, নির্দিষ্ট আকার ও আয়তন এবং অনমনীয়তা দ্বারা সংজ্ঞায়িত।" />
          </div>
        </div>

        {/* Column 2 */}
        <div className="flex flex-col gap-4">
          <div className="bg-sky-100 dark:bg-sky-900/50 p-4 rounded-lg border border-sky-200 dark:border-sky-800 text-center relative">
            <Grid className="w-8 h-8 text-sky-600 dark:text-sky-400 mx-auto mb-2" />
            <h4 className="font-bold text-sky-900 dark:text-sky-100 text-sm">
              <BilingualText en="Crystalline vs Amorphous" bn="স্ফটিকাকার বনাম অস্ফটিকাকার" />
            </h4>
            <div className="hidden md:block absolute -right-6 top-1/2 -translate-y-1/2">
              <ArrowRight className="w-4 h-4 text-slate-400" />
            </div>
          </div>
          <div className="flex-1 bg-white dark:bg-slate-800 p-3 rounded-lg text-xs text-slate-600 dark:text-slate-300 border border-slate-200 dark:border-slate-700">
            <BilingualText en="Crystalline solids have long-range order and anisotropy. Amorphous solids lack order and are isotropic." bn="স্ফটিকাকার কঠিনে দীর্ঘ-পাল্লার শৃঙ্খলা এবং অসমদিকতা থাকে। অস্ফটিকাকার কঠিনে শৃঙ্খলা থাকে না এবং তারা সমদিকধর্মী।" />
          </div>
        </div>

        {/* Column 3 */}
        <div className="flex flex-col gap-4">
          <div className="bg-emerald-100 dark:bg-emerald-900/50 p-4 rounded-lg border border-emerald-200 dark:border-emerald-800 text-center relative">
            <Droplet className="w-8 h-8 text-emerald-600 dark:text-emerald-400 mx-auto mb-2" />
            <h4 className="font-bold text-emerald-900 dark:text-emerald-100 text-sm">
              <BilingualText en="Classification" bn="শ্রেণিবিভাগ" />
            </h4>
            <div className="hidden md:block absolute -right-6 top-1/2 -translate-y-1/2">
              <ArrowRight className="w-4 h-4 text-slate-400" />
            </div>
          </div>
          <div className="flex-1 bg-white dark:bg-slate-800 p-3 rounded-lg text-xs text-slate-600 dark:text-slate-300 border border-slate-200 dark:border-slate-700">
            <BilingualText en="Classified into Ionic, Metallic, Covalent, and Molecular based on the type of bonding forces." bn="বন্ধন বলের প্রকৃতির উপর ভিত্তি করে আয়নিক, ধাতব, সমযোজী এবং আণবিক শ্রেণিতে বিভক্ত।" />
          </div>
        </div>

        {/* Column 4 */}
        <div className="flex flex-col gap-4">
          <div className="bg-rose-100 dark:bg-rose-900/50 p-4 rounded-lg border border-rose-200 dark:border-rose-800 text-center">
            <Box className="w-8 h-8 text-rose-600 dark:text-rose-400 mx-auto mb-2" />
            <h4 className="font-bold text-rose-900 dark:text-rose-100 text-sm">
              <BilingualText en="Lattice & Unit Cell" bn="জালক ও একক কোষ" />
            </h4>
          </div>
          <div className="flex-1 bg-white dark:bg-slate-800 p-3 rounded-lg text-xs text-slate-600 dark:text-slate-300 border border-slate-200 dark:border-slate-700">
            <BilingualText en="The regular 3D array of lattice points forms the space lattice, generated by repeating the unit cell." bn="জালক বিন্দুগুলির নিয়মিত ত্রিমাত্রিক বিন্যাস স্থানিক জালক গঠন করে, যা একক কোষের পুনরাবৃত্তির মাধ্যমে তৈরি হয়।" />
          </div>
        </div>
      </div>
    </div>
  );
};
